name: Gamma
author: Gravitational, Inc.
description: Build & deploy a monorepo of GitHub Actions into individual repos

runs:
  using: docker
  image: 'docker://ghcr.io/ryanclark/gamma:latest'

branding:
  color: purple
  icon: terminal
